spring.thymeleaf.cache=false
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/education_rates
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false